# Generated by Django 3.2.10 on 2022-07-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_mobile', models.IntegerField()),
                ('emp_city', models.CharField(max_length=15)),
            ],
        ),
    ]
