# Generated by Django 3.2.10 on 2022-07-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
