# Generated by Django 3.2.10 on 2022-07-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0002_alter_employee_emp_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_mobile',
            field=models.IntegerField(),
        ),
    ]
